# Generated by Django 5.1.3 on 2025-02-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_vlog_dislikes_remove_vlog_likes_vlog_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlog',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='vlog',
            name='likes',
        ),
        migrations.AddField(
            model_name='vlog',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vlog',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
