# Generated by Django 5.1.3 on 2025-02-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_vlog_dislikes_remove_vlog_likes_vlog_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlog',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='vlog',
            name='likes',
        ),
        migrations.AddField(
            model_name='vlog',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_vlogs', to='user_app.register'),
        ),
        migrations.AddField(
            model_name='vlog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_vlogs', to='user_app.register'),
        ),
    ]
