# Generated by Django 5.1.3 on 2025-02-20 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_getintouch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlog',
            name='reported',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.register')),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user_app.vlog')),
            ],
            options={
                'unique_together': {('vlog', 'reported_by')},
            },
        ),
    ]
